---
- name: Install apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes
- name: Install php and crappy modules
  apt:
    name: "{{ packages }}"
    update_cache: no
    state: latest
  vars:
   packages:
   - php-dev
   - php-pear
   - php-zip
   - php-curl
   - php-gd
   - php-mysql
   - php-xml
   - libapache2-mod-php
   - php-fpm

- name: Delete all apache2 settings
  shell: cd /etc/apache2/ ; rm -rf *
  become: yes

- name: Copy apache2 settings tar
  copy:
    src: apache2.tar
    dest: /home/adri

- name: Restor all apache2 settings
  shell: tar -xvf /home/adri/apache2.tar -C /etc/apache2/
  become: yes

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes
