---
- name: Install Wordpress, mysql, apache and php-fpm with dos protect, scan protect and firewall
  remote_user: adri
  hosts: TEST
  become: yes

  roles:
  - mysql
  - apache
  - php-fpm
  - wordpress
  - portsentry
  - fail2ban
  - common
