---
- name: Copy wordpress tar
  copy:
    src: wordpress.tar
    dest: /home/adri/

- name: untar tar
  shell: tar -xvf /home/adri/wordpress.tar -C /var/www/html
  become: yes

- name: Restart apache
  systemd:
    name: apache2
    state: restarted
