---
- name: Copy crontab check scipt to home
  copy:
    src: update_script.sh
    dest: /home/adri/update_script.sh
    mode: a+x

- name: Copy update system script to home
  copy:
    src: crontab_monitor.sh
    dest: /home/adri/crontab_monitor.sh
    mode: a+x

- name: Copy crontab to home
  copy:
    src: cron
    dest: /home/adri/cron

- name: Set crontab
  shell: crontab /home/adri/cron
  become: yes

- name: copy sshd config to home
  copy:
    src: sshd_config
    dest: /home/adri/sshd_config

- name: overwrite sshdconfig
  shell: cp /home/adri/sshd_config /etc/ssh/sshd_config
  become: yes

- name: Install apache2
  apt:
    name: iptables-persistent
    state: latest
    update_cache: yes

- name: Copy iptables rules.v4 to home
  copy:
    src: rules.v4
    dest: /home/adri/rules.v4

- name: iptables_restore
  shell: iptables-restore < /home/adri/rules.v4
  become: yes

- name: overwrite iptable-persistent rules
  shell: cp /home/adri/rules.v4 /etc/iptables/rules.v4
  become: yes

- name: Copy netplan settings to home
  template:
    src: 50-cloud-init.yaml
    dest: /home/adri/50-cloud-init.yaml

- name: Delete old netplan settings
  shell: rm -rf /etc/netplan/*
  become: yes

- name: Copy new netplan settings
  shell: cp /home/adri/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml
  become: yes

- name: Clean home
  shell: rm /home/adri/apache2.tar /home/adri/cron /home/adri/dump.sql /home/adri/sshd_config /home/adri/wordpress.tar /home/adri/50-cloud-init.yaml /home/adri/rules.v4
  become: yes

- name: Reboot machine
  reboot:
